import { Toaster } from "react-hot-toast";
import "./globals.css";
import { AuthProvider } from "@/Context/AuthContext";
import RenderedAllModal from "@/components/Modals/RenderedAllModal";
import { AppwriteProvider } from "@/Context/AppWriteContext";
import DashboardLayoutAccountSidebar from "@/Layout/DashboardLayoutAccountSidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://unicons.iconscout.com/release/v4.0.8/css/line.css"
        />
      </head>
      <body className={` antialiased`}>
        <AuthProvider>
          <AppwriteProvider>
            <Toaster position="top-center" reverseOrder={false} />
            <DashboardLayoutAccountSidebar>{children}</DashboardLayoutAccountSidebar>
            {/* <RenderedAllModal /> */}
          </AppwriteProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
